import { SchoolRecord, SiteSettings } from '../types';

export const DEFAULT_RECORDS: SchoolRecord[] = [
  {
    id: 'rec-1',
    name: 'سجل لجنة التحصيل الدراسي',
    description: 'خطط ومؤشرات رفع نواتج التعلم وتحليل نتائج الاختبارات التشخيصية والمركزية.',
    drive_url: '',
    icon: 'GraduationCap',
    order_index: 1,
    is_published: true,
  },
  {
    id: 'rec-2',
    name: 'سجل لجنة التميز',
    description: 'معايير التميز المؤسسي والمدرسي وملفات الترشح لجوائز الأداء التعليمي.',
    drive_url: '',
    icon: 'Award',
    order_index: 2,
    is_published: true,
  },
  {
    id: 'rec-3',
    name: 'سجل النمو والمجتمعات المهنية',
    description: 'ورش العمل وبرامج التطوير المهني المستمر ومجتمعات التعلم التخصصية.',
    drive_url: '',
    icon: 'Users',
    order_index: 3,
    is_published: true,
  },
  {
    id: 'rec-4',
    name: 'سجل لجنة التوجيه والإرشاد',
    description: 'برامج الرعاية التربوية والإرشاد النفسي والاجتماعي ومتابعة الحالات الخاصة.',
    drive_url: '',
    icon: 'HeartHandshake',
    order_index: 4,
    is_published: true,
  },
  {
    id: 'rec-5',
    name: 'سجل النشرات والتوجيهات',
    description: 'التعاميم الرسمية واللوائح التنظيمية والنشرات التربوية الصادرة عن الإدارة.',
    drive_url: '',
    icon: 'FileText',
    order_index: 5,
    is_published: true,
  },
  {
    id: 'rec-6',
    name: 'سجل متابعة الموظفات',
    description: 'سجلات الحضور والغياب، الأداء الوظيفي، والزيارات الإشرافية الدورية.',
    drive_url: '',
    icon: 'ClipboardCheck',
    order_index: 6,
    is_published: true,
  },
  {
    id: 'rec-7',
    name: 'سجل اجتماعات اللجان والفرق',
    description: 'محاضر الاجتماعات الدورية وتوزيع المهام والتوصيات ومتابعة الإنجاز.',
    drive_url: '',
    icon: 'Briefcase',
    order_index: 7,
    is_published: true,
  },
  {
    id: 'rec-8',
    name: 'خطة الاستعداد لكل فصل دراسي',
    description: 'استعدادات بداية الفصول الدراسية وتجهيز البيئة المدرسية والمقررات.',
    drive_url: '',
    icon: 'CalendarCheck',
    order_index: 8,
    is_published: true,
  },
  {
    id: 'rec-9',
    name: 'البطاقة التعريفية للمدرسة',
    description: 'البيانات الأساسية للمدرسة، الهيكل التنظيمي، الطاقة الاستيعابية والإحصائيات.',
    drive_url: '',
    icon: 'IdCard',
    order_index: 9,
    is_published: true,
  },
  {
    id: 'rec-10',
    name: 'سجل العهد المدرسية',
    description: 'توثيق العهد العينية والتجهيزات المدرسية والمختبرات وأجهزة التقنية.',
    drive_url: '',
    icon: 'PackageCheck',
    order_index: 10,
    is_published: true,
  },
  {
    id: 'rec-11',
    name: 'سجل الميزانية التشغيلية',
    description: 'بنود الصرف والميزانية التشغيلية وفواتير المشتريات المعتمدة.',
    drive_url: '',
    icon: 'Receipt',
    order_index: 11,
    is_published: true,
  },
  {
    id: 'rec-12',
    name: 'سجل الانضباط المدرسي',
    description: 'متابعة انتظام الطالبات، إجراءات الحد من الغياب، وحوافز الالتزام.',
    drive_url: '',
    icon: 'ShieldCheck',
    order_index: 12,
    is_published: true,
  },
  {
    id: 'rec-13',
    name: 'سجل الإذاعة المدرسية',
    description: 'جدول الفعاليات الصباحية والبرامج الإذاعية المثرية ومشاركات الفصول.',
    drive_url: '',
    icon: 'Mic',
    order_index: 13,
    is_published: true,
  },
  {
    id: 'rec-14',
    name: 'قالب الخطة الفصلية',
    description: 'نماذج توزيع المناهج والجداول والخطط الزمنية للفصول الدراسية.',
    drive_url: '',
    icon: 'LayoutTemplate',
    order_index: 14,
    is_published: true,
  },
  {
    id: 'rec-15',
    name: 'سجل الشراكات المجتمعية',
    description: 'اتفاقيات التعاون مع المجتمع المحلي ومبادرات مجلس أولياء الأمور.',
    drive_url: '',
    icon: 'Handshake',
    order_index: 15,
    is_published: true,
  },
  {
    id: 'rec-16',
    name: 'سجل الخطة التشغيلية',
    description: 'الأهداف الإستراتيجية للمدرسة والمشاريع التطويرية ومؤشرات قياس الأداء.',
    drive_url: '',
    icon: 'TrendingUp',
    order_index: 16,
    is_published: true,
  },
  {
    id: 'rec-17',
    name: 'سجل القرارات والتكليفات',
    description: 'القرارات الإدارية الداخلية وتكليفات فرق العمل واللجان المتخصصة.',
    drive_url: '',
    icon: 'FileCheck',
    order_index: 17,
    is_published: true,
  },
];

export const DEFAULT_SETTINGS: SiteSettings = {
  school_name: 'مدرسة التميز والإبداع',
  site_title: 'بوابة المدرسة الإلكترونية والسجلات الإدارية',
  site_description: 'المنصة الرقمية الموحدة للسجلات المدرسية والإشرافية والإدارية',
  // Elegant modern high-resolution architectural school building facade photo
  hero_image_url: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1920&q=80',
  hero_image_alt: 'المبنى الرئيسي للمدرسة والفناء الخارجي',
  records_intro:
    '«أهلًا بكم في بوابة السجلات الإدارية والمدرسية، التي تهدف إلى تنظيم السجلات والوثائق المدرسية وتيسير الوصول إليها إلكترونيًا، بما يسهم في رفع كفاءة العمل الإداري، وتعزيز جودة الأداء، وتسهيل متابعة الخطط والبرامج واللجان المدرسية. وقد خُصصت هذه البوابة لتجميع السجلات الإدارية في مكان واحد، بما يحقق سهولة الوصول إليها والاستفادة منها، ويدعم التنظيم والتوثيق والمتابعة المستمرة».',
  vision_text:
    '«أن تكون المدرسة بيئة تعليمية رائدة ومحفزة، تحقق التميز في الأداء المدرسي، وترتقي بمستوى التحصيل الدراسي، وتنمي مهارات الطالبات، وتعزز الإبداع والمسؤولية والشراكة المجتمعية، وفق مستهدفات التعليم ورؤية المملكة العربية السعودية 2030».',
  mission_text:
    '«تقديم تعليم نوعي في بيئة مدرسية آمنة ومحفزة، من خلال تطبيق الممارسات التعليمية الفاعلة، وتطوير الأداء المهني، وتعزيز الانضباط المدرسي، وتفعيل الشراكة مع الأسرة والمجتمع، بما يسهم في بناء شخصية متوازنة ومتميزة، وتحقيق نواتج تعلم عالية الجودة».',
  theme: {
    primary_color: '#0d9488', // emerald / teal
    secondary_color: '#0f172a', // deep slate
    background_color: '#f8fafc', // slate-50
    card_radius: 'xl',
    font_size: 'base',
    show_icons: true,
  },
  navigation: {
    home_title: 'الرئيسية',
    records_title: 'السجلات الإدارية',
    vision_title: 'الرؤية والرسالة',
    home_visible: true,
    records_visible: true,
    vision_visible: true,
  },
  contact: {
    phone: '0112345678',
    email: 'info@school.edu.sa',
    twitter_x: 'https://twitter.com',
    whatsapp: '966500000000',
    telegram: '',
    location: 'المملكة العربية السعودية',
  },
};
